### ISSUE TITLE
Continuous "Loading" status

### ISSUE THREAD

**Issue by jeremyfritzen** [lgmorand/MMM-Transilien#2]
Hi,

Since this morning, my Raspberry Pi mirror can't display the next trains any more.
My Raspberry Pi is still well connected to the Internet (other modules work well, as the news feed).

I don't know how to troubleshoot the issue or to see the module logs.

Does anyone have the same issue today?

Thank you very much

Jeremy

**Comment by FlaFla15** [comment]
Hi Jeremy,
It's working fine for me. did you try to "refresh" the MM interface ? Did you change something in you configuration ?
Any error message here: /home/pi/.pm2/logs ?

**Comment by jeremyfritzen** [comment]
Hi,
I tried a raspberry pi reboot but the issue is still occuring.

Indeed, I have 1 file "mm-error-0.log" in logs directory.
It's very verbose but I can see that the following lines occur several times:


```
TypeError: Cannot read property 'length' of undefined
    at Class.processTransports (/home/pi/MagicMirror/modules/MMM-Transilien/node_helper.js:76:41)
    at /home/pi/MagicMirror/modules/MMM-Transilien/node_helper.js:45:26
    at Request.handleRequestResponse [as _callback] (/home/pi/MagicMirror/modules/MMM-Transilien/node_modules/unirest/index.js:463:26)
    at Request.self.callback (/home/pi/MagicMirror/modules/MMM-Transilien/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-Transilien/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-Transilien/node_modules/request/request.js:965:12)
```

Another thing: I tried to ping api.transilien.com address and it doesn't answer, either on my local Internet connection or with my mobile phone.

Then I think it's a problem on Transilien server side but then, I don't understand why it's working with you. It's very strange!

Thank you for your help

**Comment by lgmorand** [comment]
"Cannot read property 'length' of undefined" means that it did not receive any good json from the API, either because it is not well formatted or because I did not received at all. In your case, you can't access the API, that's definitely an issue with you connection, your DNS or something else.

**Comment by jeremyfritzen** [comment]
Hi,

Thank you for your answers.
I think the issue was on the Transilien server side because the issue was automatically fixed without changing anything.

Thank you!
